= README - RANK APPLICATION

:githubdir: https://github.com/rafal-perkowski
:projectdir: /RankApplication
:blobmasterdir: /blob/master
:imgdir: img
:srcdir: src

## Wstęp

W ramach kolejnego etapu kursu Back-End Developer PWN należało wykonać aplikację w języku Python łączącą użytkownika ze stworzoną w projekcie nr 2 bazą MySQL.

## Projekt nr 3: Aplikacja w języku Python łącząca z bazą danych

. Implementacja programu w Pythonie obsługującego zapytania wykonywane na bazie danych stworzonej w ramach poprzedniego projektu obejmującego:
. Panel logowania, który będzie umożliwiał wpisanie loginu i hasła, a następnie będzie porównywał te wartości z zawartością tabeli logowanie.
. Menu obsługi gdzie będzie możliwe podjęcie przez użytkownika decyzji co ma być wykonane. Np. wyświetlanie tabeli, wykonanie zapytania, wyjście z programu, itp.
. Dodatkowe: przypisanie różnych uprawnień dla wybranych loginów tak aby byli użytkownicy, którzy mogą tylko przeglądać tabele i tacy którzy mogą wprowadzać zmiany w rekordach.

## Top 500 Rank (aplikacja)

### Opis aplikacji

W projekcie została wykonana aplikacja w języku Python łącząca z bazą danych rankingu superkomputerów, której implementacja została zamieszczona w repozytorium *_RankDatabase_*.

Aplikacja powstała w zgodności z modelem/wzorcem MVC (Model View Controller).

### Model MVC

W pliku źródłowym link:{srcdir}/top500rank.py[top500rank.py] zaimplementowano 8 następujących klas:

====
* *DBModel* - klasa odwzorowująca model bazy danych w postaci list nazw tabel/widoków i kolumn wraz z metodami, które na nich operują.
* *DBQuery* - klasa implementująca wzorce TCV (Table Column Value) zapytań do bazy danych i generująca na ich podstawie oraz krotki konfiguracyjnej wykonywalną postać zapytania.
* *DBConnection* - klasa służąca do nawiązywania i zamykania połączenia z bazą danych.
* *DBViewController* - klasa kontrolera wyświetlania grupująca metody formatowania i wydruku tabel bazy danych w oknie konsoli.
* *DBLoginController* - klasa kontrolera logowania obsługująca autentykację połączenia z bazą danych.
* *DBAdminController* - klasa kontrolera menu administratora obsługująca jego dane wejściowe, wykonująca zapytania w bazie danych i wyświetlająca ich wyniki.
* *DBUserController* - klasa kontrolera menu użytkownika obsługująca jego dane wejściowe, wykonująca zapytania w bazie danych i wyświetlająca ich wyniki.
* *DBMenu* - klasa organizująca i wyświetlająca kilkupoziomowe menu administratora i użytkownika.
====

## Zrzuty ekranu

W katalogu link:{imgdir}[[_img_]] zostały umieszczone zrzuty ekranu aplikacji:

* Okno logowania aplikacji link:{imgdir}/01-login-window.png[[_img_]]
* Menu administratora link:{imgdir}/02-admin-menu.png[[_img_]]
* Menu administratora (tabela 1) link:{imgdir}/03-admin-table-1.png[[_img_]]
* Menu administratora (tabela 2) link:{imgdir}/04-admin-table-2.png[[_img_]]
* Menu administratora (tabela 3) link:{imgdir}/05-admin-table-3.png[[_img_]]
* Menu użytkownika link:{imgdir}/06-user-menu.png[[_img_]]
* Menu użytkownika (tabela 1.1) link:{imgdir}/07-user-table-1.png[[_img_]]
* Menu użytkownika (tabela 1.2) link:{imgdir}/08-user-table-2.png[[_img_]]
* Menu użytkownika (tabela 2.1) link:{imgdir}/09-user-table-3.png[[_img_]]
* Menu użytkownika (tabela 2.2) link:{imgdir}/10-user-table-4.png[[_img_]]
* Menu użytkownika (tabela 3.1) link:{imgdir}/11-user-table-5.png[[_img_]]
* Menu użytkownika (tabela 3.2) link:{imgdir}/12-user-table-6.png[[_img_]]
* Menu użytkownika (tabela 4.1) link:{imgdir}/13-user-table-7.png[[_img_]]
* Menu użytkownika (tabela 4.2) link:{imgdir}/14-user-table-8.png[[_img_]]

## Materiały

* "Python - prezentacja" - ~300 slajdów z kursu PWN Back-End Developer.
* https://docs.python.org/3/[Python 3.6.4 documentation] - dokumentacja języka Python.

## Narzędzia

* https://eclipse.org/downloads/packages/technologyeppdownloadsreleaseoxygenreclipse-java-oxygen-r-win32-x8664zip[Eclipse IDE for Java Developers, Oxygen.1a Release (4.7.1a)] - zintegrowane środowisko programistyczne umożliwiające rozwijanie aplikacji w wielu językach programowania (poprzez tzw. wtyczki, _ang. plugins_).
* https://sourceforge.net/projects/pydev/files/pydev/PyDev%206.1.0/[PyDev - Python Development environment (6.1.0)] - perspektywa/plugin dla tworzenia aplikacji w języku Python w środowisku Eclipse.
* https://www.python.org/downloads/release/python-344/[Python 3.4.4] - interpreter języka Python wraz z zewnętrznymi bibliotekami

## Uruchomienie aplikacji

### Konfiguracja

Program działa razem z bazą danych *_top500rank_* sprządzoną w ramach projektu *_RankDatabase_*.

NOTE: Dodatkowo należy skonfigurować własne hasło dostępu do serwera bazy danych w pliku link:{srcdir}/logindata.py[logindata.py] dla konta *_root_* (w miejsce trzech gwiazdek) .

Oczywiście zależnie od potrzeb można skonfigurować także pozostałe parametry logowania z listy *_loginList_*:

====
* host - adres komputera z serwerem bazy danych (_domyślna wartość: **localhost**_)
* user - nazwa użytkownika na serwerze bazy danych (_domyślna wartość: **root**_)
* password - hasło użytkownika na serwerze bazy danych (_wymagana konfiguracja_)
* db - nazwa bazy danych na serwerze z którą chcemy się połączyć (_domyślna wartość: **top500rank**_)
* charset - kodowanie znaków po nawiązaniu połączenia z bazą danych (_domyślna wartość: **utf8mb4**_)
* port - numer portu na serwerze bazy danych (_domyślna wartość: **3306**_)
====

Po skonfigurowaniu i nawiązaniu połączenia z bazą danych pojawi się logo aplikacji i konsola logowania do bazy danych.

### Logowanie

Dostępne są dwa wewnętrzne (w tabeli *_rankusers_* bazy danych) konta logowania demonstrujące oba typy interakcji z aplikacją:

====
* Administrator - może wyświetlać, dodawać, modyfikować i usuwać rekordy w tabelach bazy danych +

Dane logowania: _[Login]: admin, [Password]: admin123_

* Użytkownik - uzyskuje dostęp do kilku przykładowych widoków z rankingami z bazy danych +

Dane logowania: _[Login]: user, [Password]: user123_
====

## Informacje dodatkowe

Projekt został zrealizowany na dzień **11 grudnia 2017r.**
